name: 'Check Package Version Upgraded'
description: 'Checks if the version in package.json is greater than the version in the specified branch.'
inputs:
  target_branch:
    description: 'The target branch to compare the version against.'
    required: true
    default: 'main'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensure full history for comparison, might increase action runtime

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Fetch target branch and compare versions
      run: |
        git fetch --depth=1 origin ${{ github.base_ref }}
        TARGET_VERSION=$(git show origin/${{github.base_ref}}:package.json | jq -r '.version')
        echo "Target branch: ${{github.base_ref}}"
        echo "Target version: $TARGET_VERSION"
        SOURCE_VERSION=$(git show origin/${{github.head_ref}}:package.json | jq -r '.version')
        echo "Source branch: ${{github.head_ref}}"
        echo "Package version: $SOURCE_VERSION"
        
        if [ "$(printf '%s\n' "$SOURCE_VERSION" "$TARGET_VERSION" | sort -V | head -n1)" = "$SOURCE_VERSION" ]; then
          echo "Error: Package version ($PACKAGE_VERSION) must be greater than the main branch version ($TARGET_VERSION)."
          exit 1
        else
          echo "Version check passed. Current version ($SOURCE_VERSION) is greater than the main branch version ($TARGET_VERSION)."
        fi
      shell: bash
